// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb_router_multibeat_hold.h for the primary calling header

#ifndef VERILATED_VTB_ROUTER_MULTIBEAT_HOLD___024ROOT_H_
#define VERILATED_VTB_ROUTER_MULTIBEAT_HOLD___024ROOT_H_  // guard

#include "verilated.h"
class Vtb_router_multibeat_hold_noc_params_pkg;


class Vtb_router_multibeat_hold__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtb_router_multibeat_hold___024root final {
  public:
    // CELLS
    Vtb_router_multibeat_hold_noc_params_pkg* __PVT__noc_params_pkg;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        CData/*4:0*/ tb_router_multibeat_hold__DOT__in_valid;
        CData/*4:0*/ tb_router_multibeat_hold__DOT__out_ready;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_hb23073c6__0;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_h0e6bbddf__0;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_h39c5bd67__0;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_hf924bb40__0;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_hefd1f2b4__0;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_h3c4873bc__0;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_hef968210__0;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_h4b2015cb__0;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_h85284c16__0;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_hfcb635f7__0;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_hffee7e95__0;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_hd76b91b7__0;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_h728332b5__0;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_h298f90ab__0;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_hbb3438a7__0;
        CData/*4:0*/ tb_router_multibeat_hold__DOT__dut__DOT__in_ready;
        CData/*4:0*/ tb_router_multibeat_hold__DOT__dut__DOT__in_reg_valid;
        QData/*39:0*/ tb_router_multibeat_hold__DOT__dut__DOT__fifo_push;
        QData/*39:0*/ tb_router_multibeat_hold__DOT__dut__DOT__fifo_pop;
        QData/*39:0*/ tb_router_multibeat_hold__DOT__dut__DOT__fifo_empty;
        QData/*39:0*/ tb_router_multibeat_hold__DOT__dut__DOT__fifo_full;
        CData/*4:0*/ tb_router_multibeat_hold__DOT__dut__DOT__out_reg_valid;
        CData/*7:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__req_vec;
        CData/*7:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__hold_vec;
        CData/*7:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__grant_vec;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__has_candidate;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__has_candidate;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__candidate_valid_out;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__unnamedblk25__DOT__unnamedblk26__DOT__want_vc;
        CData/*7:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__req_vec;
        CData/*7:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__hold_vec;
        CData/*7:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__grant_vec;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__has_candidate;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__has_candidate;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__candidate_valid_out;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__unnamedblk25__DOT__unnamedblk26__DOT__want_vc;
        CData/*7:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__req_vec;
        CData/*7:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__hold_vec;
        CData/*7:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__grant_vec;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__has_candidate;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__has_candidate;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__candidate_valid_out;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__unnamedblk25__DOT__unnamedblk26__DOT__want_vc;
        CData/*7:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__req_vec;
        CData/*7:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__hold_vec;
        CData/*7:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__grant_vec;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__has_candidate;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__has_candidate;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__candidate_valid_out;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__unnamedblk25__DOT__unnamedblk26__DOT__want_vc;
        CData/*7:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__req_vec;
        CData/*7:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__hold_vec;
        CData/*7:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__grant_vec;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__has_candidate;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__has_candidate;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__candidate_valid_out;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__unnamedblk25__DOT__unnamedblk26__DOT__want_vc;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__cnt;
    };
    struct {
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__do_pop;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__do_pop;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__do_pop;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*4:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__do_pop;
        CData/*4:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__do_pop;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__do_pop;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__do_pop;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__do_pop;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__do_pop;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__do_pop;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__do_pop;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__wr_ptr;
    };
    struct {
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*4:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__do_pop;
        CData/*4:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__do_pop;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__do_pop;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__do_pop;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__do_pop;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__do_pop;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__do_pop;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__do_pop;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*4:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__do_pop;
        CData/*4:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__do_pop;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__do_pop;
    };
    struct {
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__do_pop;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__do_pop;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__do_pop;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__do_pop;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__do_pop;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*4:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__do_pop;
        CData/*4:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__do_pop;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__do_pop;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__do_pop;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__do_pop;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__cnt;
    };
    struct {
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__do_pop;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__do_pop;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*1:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__do_pop;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*4:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__do_pop;
        CData/*4:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__do_pop;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__do_pop;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__do_pop;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__wr_ptr;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__rd_ptr;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__cnt;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__do_push;
        CData/*0:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__do_pop;
        CData/*3:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__free_tmp;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__arb_i__DOT__rr_ptr;
        CData/*7:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__arb_i__DOT__grant_comb;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__arb_i__DOT__rr_ptr;
        CData/*7:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__arb_i__DOT__grant_comb;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__arb_i__DOT__rr_ptr;
        CData/*7:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__arb_i__DOT__grant_comb;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__arb_i__DOT__rr_ptr;
        CData/*7:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__arb_i__DOT__grant_comb;
        CData/*2:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__arb_i__DOT__rr_ptr;
        CData/*7:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__arb_i__DOT__grant_comb;
        CData/*3:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__4__dst_node;
        CData/*3:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__7__dst_node;
        CData/*3:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__9__dst_node;
        CData/*3:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__11__dst_node;
        CData/*3:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__19__dst_node;
        CData/*3:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__22__dst_node;
        CData/*3:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__24__dst_node;
        CData/*3:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__26__dst_node;
        CData/*3:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__34__dst_node;
    };
    struct {
        CData/*3:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__37__dst_node;
        CData/*3:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__39__dst_node;
        CData/*3:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__41__dst_node;
        CData/*3:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__49__dst_node;
        CData/*3:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__52__dst_node;
        CData/*3:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__54__dst_node;
        CData/*3:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__56__dst_node;
        CData/*3:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__64__dst_node;
        CData/*3:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__67__dst_node;
        CData/*3:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__69__dst_node;
        CData/*3:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__71__dst_node;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_n__0;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        VlWide<20>/*639:0*/ tb_router_multibeat_hold__DOT__in_flit;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__cycle;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_he3e12c26__0;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_h3a4972a0__0;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_hc4e86825__0;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_hc8ae3ad1__0;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_he4eeb775__0;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_hbf148660__0;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_h33266093__0;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_h313a7dec__0;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_h44fffa75__0;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_hbce0f0a3__0;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT____Vlvbound_hbae1d3de__0;
        VlWide<20>/*639:0*/ tb_router_multibeat_hold__DOT__dut__DOT__in_reg_flit;
        VlWide<160>/*5119:0*/ tb_router_multibeat_hold__DOT__dut__DOT__fifo_din;
        VlWide<160>/*5119:0*/ tb_router_multibeat_hold__DOT__dut__DOT__fifo_dout;
        VlWide<20>/*639:0*/ tb_router_multibeat_hold__DOT__dut__DOT__out_reg_flit;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__best_qos;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__candidate_flit;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__dest_port;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__candidate_flit;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__dest_port;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__selected_vc;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__candidate_flit_out;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__unnamedblk12__DOT__dest_port;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__unnamedblk12__DOT__unnamedblk13__DOT__sip;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__unnamedblk18__DOT__sip;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__unnamedblk18__DOT__unnamedblk19__DOT__dest_port;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__best_qos;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__candidate_flit;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__dest_port;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__candidate_flit;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__dest_port;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__selected_vc;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__candidate_flit_out;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__unnamedblk12__DOT__dest_port;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__unnamedblk12__DOT__unnamedblk13__DOT__sip;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__unnamedblk18__DOT__sip;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__unnamedblk18__DOT__unnamedblk19__DOT__dest_port;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__best_qos;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__candidate_flit;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__dest_port;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__candidate_flit;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__dest_port;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__selected_vc;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__candidate_flit_out;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__unnamedblk12__DOT__dest_port;
    };
    struct {
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__unnamedblk12__DOT__unnamedblk13__DOT__sip;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__unnamedblk18__DOT__sip;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__unnamedblk18__DOT__unnamedblk19__DOT__dest_port;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__best_qos;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__candidate_flit;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__dest_port;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__candidate_flit;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__dest_port;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__selected_vc;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__candidate_flit_out;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__unnamedblk12__DOT__dest_port;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__unnamedblk12__DOT__unnamedblk13__DOT__sip;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__unnamedblk18__DOT__sip;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__unnamedblk18__DOT__unnamedblk19__DOT__dest_port;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__best_qos;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__candidate_flit;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__dest_port;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__candidate_flit;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__dest_port;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__selected_vc;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__candidate_flit_out;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__unnamedblk12__DOT__dest_port;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__unnamedblk12__DOT__unnamedblk13__DOT__sip;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__unnamedblk18__DOT__sip;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__unnamedblk18__DOT__unnamedblk19__DOT__dest_port;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT____Vlvbound_h6746f861__0;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT____Vlvbound_h6746f861__0;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT____Vlvbound_h6746f861__0;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT____Vlvbound_h6746f861__0;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
    };
    struct {
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        VlWide<4>/*127:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT____Vlvbound_h6746f861__0;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__unnamedblk1__DOT__free_i;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__arb_i__DOT__unnamedblk1__DOT__unnamedblk2__DOT__idx_int;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__arb_i__DOT__unnamedblk3__DOT__next_ptr_int;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__arb_i__DOT__unnamedblk1__DOT__unnamedblk2__DOT__idx_int;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__arb_i__DOT__unnamedblk3__DOT__next_ptr_int;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__arb_i__DOT__unnamedblk1__DOT__unnamedblk2__DOT__idx_int;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__arb_i__DOT__unnamedblk3__DOT__next_ptr_int;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__arb_i__DOT__unnamedblk1__DOT__unnamedblk2__DOT__idx_int;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__arb_i__DOT__unnamedblk3__DOT__next_ptr_int;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__arb_i__DOT__unnamedblk1__DOT__unnamedblk2__DOT__idx_int;
        IData/*31:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__arb_i__DOT__unnamedblk3__DOT__next_ptr_int;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__2__flit;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__3__flit;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__4__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__4__dst_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__4__dst_y;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__5__flit;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__6__flit;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__7__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__7__dst_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__7__dst_y;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__8__flit;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__9__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__9__mesh_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__9__dst_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__9__dst_y;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__10__flit;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__11__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__11__mesh_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__11__dst_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__11__dst_y;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__17__flit;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__18__flit;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__19__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__19__dst_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__19__dst_y;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__20__flit;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__21__flit;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__22__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__22__dst_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__22__dst_y;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__23__flit;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__24__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__24__mesh_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__24__dst_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__24__dst_y;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__25__flit;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__26__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__26__mesh_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__26__dst_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__26__dst_y;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__32__flit;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__33__flit;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__34__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__34__dst_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__34__dst_y;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__35__flit;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__36__flit;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__37__Vfuncout;
    };
    struct {
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__37__dst_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__37__dst_y;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__38__flit;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__39__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__39__mesh_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__39__dst_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__39__dst_y;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__40__flit;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__41__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__41__mesh_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__41__dst_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__41__dst_y;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__47__flit;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__48__flit;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__49__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__49__dst_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__49__dst_y;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__50__flit;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__51__flit;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__52__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__52__dst_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__52__dst_y;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__53__flit;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__54__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__54__mesh_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__54__dst_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__54__dst_y;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__55__flit;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__56__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__56__mesh_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__56__dst_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__56__dst_y;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__62__flit;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__63__flit;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__64__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__64__dst_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__64__dst_y;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__65__flit;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__66__flit;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__67__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__67__dst_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__67__dst_y;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__68__flit;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__69__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__69__mesh_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__69__dst_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__69__dst_y;
        VlWide<4>/*127:0*/ __Vfunc_extract_hdr__70__flit;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__71__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__71__mesh_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__71__dst_x;
        IData/*31:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__71__dst_y;
        IData/*31:0*/ __Vdly__tb_router_multibeat_hold__DOT__cycle;
        IData/*31:0*/ __VactIterCount;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__hdr;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__hdr_c;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__hdr_reg;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__hdr_c;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__hdr_reg;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__unnamedblk12__DOT__h;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__unnamedblk12__DOT__hr;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__unnamedblk18__DOT__unnamedblk19__DOT__h;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__unnamedblk18__DOT__unnamedblk19__DOT__unnamedblk20__DOT__hr;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__unnamedblk25__DOT__unnamedblk26__DOT__hdr_r;
    };
    struct {
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__hdr_c;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__hdr_reg;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__hdr_c;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__hdr_reg;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__unnamedblk12__DOT__h;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__unnamedblk12__DOT__hr;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__unnamedblk18__DOT__unnamedblk19__DOT__h;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__unnamedblk18__DOT__unnamedblk19__DOT__unnamedblk20__DOT__hr;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__unnamedblk25__DOT__unnamedblk26__DOT__hdr_r;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__hdr_c;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__hdr_reg;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__hdr_c;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__hdr_reg;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__unnamedblk12__DOT__h;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__unnamedblk12__DOT__hr;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__unnamedblk18__DOT__unnamedblk19__DOT__h;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__unnamedblk18__DOT__unnamedblk19__DOT__unnamedblk20__DOT__hr;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__unnamedblk25__DOT__unnamedblk26__DOT__hdr_r;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__hdr_c;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__hdr_reg;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__hdr_c;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__hdr_reg;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__unnamedblk12__DOT__h;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__unnamedblk12__DOT__hr;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__unnamedblk18__DOT__unnamedblk19__DOT__h;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__unnamedblk18__DOT__unnamedblk19__DOT__unnamedblk20__DOT__hr;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__unnamedblk25__DOT__unnamedblk26__DOT__hdr_r;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__hdr_c;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__unnamedblk5__DOT__unnamedblk6__DOT__unnamedblk7__DOT__hdr_reg;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__hdr_c;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__hdr_reg;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__unnamedblk12__DOT__h;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__unnamedblk12__DOT__hr;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__unnamedblk18__DOT__unnamedblk19__DOT__h;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__unnamedblk18__DOT__unnamedblk19__DOT__unnamedblk20__DOT__hr;
        QData/*35:0*/ tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__unnamedblk25__DOT__unnamedblk26__DOT__hdr_r;
        QData/*35:0*/ __Vfunc_extract_hdr__2__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__2__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__3__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__3__hdr;
        QData/*35:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__4__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__5__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__5__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__6__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__6__hdr;
        QData/*35:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__7__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__8__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__8__hdr;
        QData/*35:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__9__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__10__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__10__hdr;
        QData/*35:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__11__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__17__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__17__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__18__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__18__hdr;
        QData/*35:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__19__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__20__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__20__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__21__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__21__hdr;
        QData/*35:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__22__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__23__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__23__hdr;
    };
    struct {
        QData/*35:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__24__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__25__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__25__hdr;
        QData/*35:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__26__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__32__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__32__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__33__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__33__hdr;
        QData/*35:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__34__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__35__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__35__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__36__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__36__hdr;
        QData/*35:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__37__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__38__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__38__hdr;
        QData/*35:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__39__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__40__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__40__hdr;
        QData/*35:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__41__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__47__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__47__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__48__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__48__hdr;
        QData/*35:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__49__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__50__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__50__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__51__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__51__hdr;
        QData/*35:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__52__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__53__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__53__hdr;
        QData/*35:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__54__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__55__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__55__hdr;
        QData/*35:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__56__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__62__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__62__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__63__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__63__hdr;
        QData/*35:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__64__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__65__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__65__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__66__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__66__hdr;
        QData/*35:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__67__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__68__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__68__hdr;
        QData/*35:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__69__hdr;
        QData/*35:0*/ __Vfunc_extract_hdr__70__Vfuncout;
        QData/*35:0*/ __Vfunc_extract_hdr__70__hdr;
        QData/*35:0*/ __Vfunc_tb_router_multibeat_hold__DOT__dut__DOT__route_port__71__hdr;
        VlUnpacked<SData/*15:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__age_vec;
        VlUnpacked<SData/*15:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__age_vec;
        VlUnpacked<SData/*15:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__age_vec;
        VlUnpacked<SData/*15:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__age_vec;
        VlUnpacked<SData/*15:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__age_vec;
        VlUnpacked<VlWide<4>/*127:0*/, 4> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 4> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 4> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 16> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 12> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__mem;
    };
    struct {
        VlUnpacked<VlWide<4>/*127:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__0__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 4> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 4> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 4> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 16> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 12> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__1__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 4> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 4> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 4> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 16> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 12> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__2__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 4> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 4> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 4> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 16> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 12> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__3__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 4> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__0__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 4> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__1__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 4> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__2__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 16> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__3__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__4__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__5__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 12> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__6__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<VlWide<4>/*127:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_PORTS__BRA__4__KET____DOT__GEN_VCS__BRA__7__KET____DOT__fifo_i__DOT__mem;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
        VlUnpacked<CData/*0:0*/, 3> __Vm_traceActivity;
    };

    // INTERNAL VARIABLES
    Vtb_router_multibeat_hold__Syms* vlSymsp;
    const char* vlNamep;

    // PARAMETERS
    static constexpr VlUnpacked<IData/*31:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__VC_QOS = {{
        1U, 1U, 1U, 1U,
        1U, 1U, 1U, 1U
    }};
    static constexpr VlUnpacked<IData/*31:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__0__KET____DOT__arb_i__DOT__WEIGHTS = {{
        0U, 4U, 3U, 6U,
        2U, 4U, 5U, 2U
    }};
    static constexpr VlUnpacked<IData/*31:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__1__KET____DOT__arb_i__DOT__WEIGHTS = {{
        0U, 4U, 3U, 6U,
        2U, 4U, 5U, 2U
    }};
    static constexpr VlUnpacked<IData/*31:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__2__KET____DOT__arb_i__DOT__WEIGHTS = {{
        0U, 4U, 3U, 6U,
        2U, 4U, 5U, 2U
    }};
    static constexpr VlUnpacked<IData/*31:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__3__KET____DOT__arb_i__DOT__WEIGHTS = {{
        0U, 4U, 3U, 6U,
        2U, 4U, 5U, 2U
    }};
    static constexpr VlUnpacked<IData/*31:0*/, 8> tb_router_multibeat_hold__DOT__dut__DOT__GEN_OUTPUT_PORT__BRA__4__KET____DOT__arb_i__DOT__WEIGHTS = {{
        0U, 4U, 3U, 6U,
        2U, 4U, 5U, 2U
    }};

    // CONSTRUCTORS
    Vtb_router_multibeat_hold___024root(Vtb_router_multibeat_hold__Syms* symsp, const char* namep);
    ~Vtb_router_multibeat_hold___024root();
    VL_UNCOPYABLE(Vtb_router_multibeat_hold___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
